apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DATABASE_URL: "postgresql+psycopg://sentineluser:sentineluser123!!!@db:5432/cloudsentinel"
  SECRET_KEY: "CloudSentinel"
  JWT_SECRET_KEY: "cloudsentineljwt"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudsentinel-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudsentinel-backend
  template:
    metadata:
      labels:
        app: cloudsentinel-backend
    spec:
      containers:
      - name: backend
        image: cloudsentinel-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: cloudsentinel-backend
