"""drift events table

Revision ID: b6066c411c3c
Revises: 
Create Date: 2026-05-31 10:49:43.989235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6066c411c3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drift_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource', sa.String(length=200), nullable=True),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.alter_column('scan_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.alter_column('scan_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('drift_events')
    # ### end Alembic commands ###
